import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>

      <style jsx>
        {`
          h2{
            font-size: 40px;
          }
          h3{
            font-size: 28px ;
          }
        `}
      </style>
      
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <Link href="/"> <li>Home</li>   </Link>
          <Link href="/about"> <li>About</li> </Link>
          <Link href="/blog"> <li>Blog</li> </Link>
          <Link href="contact"> <li>Contact</li> </Link>
        </ul>
      </nav>

      <main className={styles.main}>
      
        <h1 className={styles.title}>
            Hunting Coder
        </h1>

      <div className={styles.imageWrapper}>
          <Image  className = {styles.myImg}  
          src="/photo.webp"
          width = {237}
          height = {159}
          alt = "Coder's Image"
        
          />
      </div>

        <h2 className={styles.description}>
          A blog for hunting coders by a hunting coder
        </h2>

        <h2>Popular Blogs</h2>
        <h3 className={styles.description}>
          A blog for hunting coders by a hunting coder
        </h3>
        <h3 className={styles.description}>
          A blog for hunting coders by a hunting coder
        </h3>
        <h3 className={styles.description}>
          A blog for hunting coders by a hunting coder
        </h3>

      </main>

      
    </div>
  )
}