import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
            Hunting Coder
        </h1>

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <h2>Popular blogs
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>
        
        </h2>


      </main>

      
    </div>
  )
}